# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([7, 8, 9])

# Create a 2-dimensional NumPy array using np.array()
b = np.array([[10.7, 12.6, 14.8],
             [170, 117, 182]])

# Create a 3-dimensional Numpy array using np.array()
c = np.array([[[21, 9, 12],
               [1, 28, 2],
               [2, 31, 12]],
              
              [[1, 3, 9],
               [15, 13, 1],
               [28, 30, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a.ndim, a.dtype.name, a.dtype, a.size, type(a), a.shape 

(1, 'int32', dtype('int32'), 3, numpy.ndarray, (3,))

In [5]:
# Attributes of 2-dimensional array
b.ndim, b.dtype.name, b.size, type(b), b.shape

(2, 'float64', 6, numpy.ndarray, (2, 3))

In [6]:
# Attributes of 3-dimensional array
c.ndim, c.dtype.name, c.size, type(c), c.shape

(3, 'int32', 18, numpy.ndarray, (2, 3, 3))

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(b)
df

0      1      2
0   10.7   12.6   14.8
1  170.0  117.0  182.0

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
d = np.array(range(0, 100, 3))
d
# otra opcion: range_array = np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(0)
e = np.random.randint(0, 10, size=(7,2))
e

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4],
       [7, 6],
       [8, 8]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(0)
f = np.random.random((3,5))
f

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [18]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
g = np.random.randint(0, 10, size=(4,6))
g

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(seed=14)
h = np.random.randint(1, 10, size=(3,7))
print("Array h:\n", h)

Array h:
 [[9 7 8 7 1 9 8]
 [7 1 8 5 1 7 5]
 [6 6 9 6 9 8 4]]


In [24]:
# Find the unique numbers in the array you just created
np.unique(h)
# np.unique(array) Devuelve los elementos únicos ordenados de una matriz.
# https://numpy.org/doc/stable/reference/generated/numpy.unique.html

array([1, 4, 5, 6, 7, 8, 9])

In [35]:
# Find the 0'th index of the latest array you created (acceder a la primera fila del arreglo h)
first_row = h[0] 
print("0'th index of the array (first row):\n", first_row)

0'th index of the array (first row):
 [9 7 8 7 1 9 8]


In [37]:
# Get the first 2 rows of latest array you created
first_2_rows = h[:2]
print("First 2 rows of the array h:\n", first_2_rows)

First 2 rows of the array h:
 [[9 7 8 7 1 9 8]
 [7 1 8 5 1 7 5]]


In [38]:
# Get the first 2 values of the first 2 rows of the latest array
first2val_1st2rows = h[:2,:2]
print("First 2 values of the first 2 rows of the array h:\n",first2val_1st2rows)

First 2 values of the first 2 rows of the array h:
 [[9 7]
 [7 1]]


In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(seed=43)
i = np.random.randint(0, 10, size=(3,5))
j = np.ones((3,5))
i, j

(array([[4, 0, 1, 5, 0],
        [3, 1, 2, 7, 0],
        [3, 2, 9, 1, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [54]:
# Add the two arrays together
sum_array = i+j 
print("The sum of the two arrays created is:\n",sum_array)

The sum of the two arrays created is:
 [[ 5.  1.  2.  6.  1.]
 [ 4.  2.  3.  8.  1.]
 [ 4.  3. 10.  2.  3.]]


In [44]:
# Create another array of ones of shape (5, 3)
k = np.ones((5,3))
k, k.shape

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 (5, 3))

In [45]:
# Try add the array of ones and the other most recent array together
j + k
# logicamente, retornará error porque los arreglos son de distinta dimension
# j es de dimension (3,5) mientras que k es de dimensión (5,3). Si se requieren
# sumar arreglos estos deben ser de la misma dimensión.

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
# ¿como lo arreglaria? cambiando la dimension de k para que coincidan, 
# trasponiendo k, por ejemplo, así:
j + k.T
j.shape, k.T.shape
# dado que ahora las dimensiones coinciden, entonces sí se puede efectuar la suma de matrices

((3, 5), (3, 5))

In [55]:
# Create another array of ones of shape (3, 5)
l = np.ones((3,5))
l

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Subtract the new array of ones from the other most recent array
print("Recordemos, el arreglo mas reciente que creamos es este:\n", sum_array)
m = sum_array - l
print("Sustraemos el nuevo arreglo de unos al arreglo anterior:\n", m)


Recordemos, el arreglo mas reciente que creamos es este:
 [[ 5.  1.  2.  6.  1.]
 [ 4.  2.  3.  8.  1.]
 [ 4.  3. 10.  2.  3.]]
Sustraemos el nuevo arreglo de unos al arreglo anterior:
 [[4. 0. 1. 5. 0.]
 [3. 1. 2. 7. 0.]
 [3. 2. 9. 1. 2.]]


In [61]:
# Multiply the ones array with the latest array
multiply_array = m * l
multiply_array

array([[4., 0., 1., 5., 0.],
       [3., 1., 2., 7., 0.],
       [3., 2., 9., 1., 2.]])

In [62]:
# Take the latest array to the power of 2 using '**'
multiply_array ** 2

array([[16.,  0.,  1., 25.,  0.],
       [ 9.,  1.,  4., 49.,  0.],
       [ 9.,  4., 81.,  1.,  4.]])

In [64]:
# Do the same thing with np.square()
n = np.square(multiply_array)
n

array([[16.,  0.,  1., 25.,  0.],
       [ 9.,  1.,  4., 49.,  0.],
       [ 9.,  4., 81.,  1.,  4.]])

In [65]:
# Find the mean of the latest array using np.mean()
np.mean(n)

13.6

In [66]:
# Find the maximum of the latest array using np.max()
np.max(n)

81.0

In [67]:
# Find the minimum of the latest array using np.min()
np.min(n)

0.0

In [68]:
# Find the standard deviation of the latest array
np.std(n)

22.03270296627266

In [69]:
# Find the variance of the latest array
np.var(n)

485.44

In [71]:
# Reshape the latest array to (3, 5, 1)
o = n.reshape(3,5,1)
o

array([[[16.],
        [ 0.],
        [ 1.],
        [25.],
        [ 0.]],

       [[ 9.],
        [ 1.],
        [ 4.],
        [49.],
        [ 0.]],

       [[ 9.],
        [ 4.],
        [81.],
        [ 1.],
        [ 4.]]])

In [73]:
# Transpose the latest array
transposed_array = o.T
transposed_array
# intercambia filas por columnas 

array([[[16.,  9.,  9.],
        [ 0.,  1.,  4.],
        [ 1.,  4., 81.],
        [25., 49.,  1.],
        [ 0.,  0.,  4.]]])

What does the transpose do?

In [76]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)

matrix1 = np.random.randint(0, 10, size=(3,3))
matrix2 = np.random.randint(0, 10, size=(3,2))

print(f"El primer arreglo es:\n{matrix1}\nMientras que el segundo es:\n{matrix2}")

El primer arreglo es:
[[5 0 3]
 [3 7 9]
 [3 5 2]]
Mientras que el segundo es:
[[4 7]
 [6 8]
 [8 1]]


In [77]:
# Perform a dot product on the two newest arrays you created
matrix3 = np.dot(matrix1, matrix2)
matrix3

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [79]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)

matrix4 = np.random.randint(0, 10, size=(4,3))
matrix5 = np.random.randint(0, 10, size=(4,3))

print(f"El primer arreglo es:\n{matrix4}\nMientras que el segundo es:\n{matrix5}")

El primer arreglo es:
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
Mientras que el segundo es:
[[8 8 1]
 [6 7 7]
 [8 1 5]
 [9 8 9]]


In [80]:
# Perform a dot product on the two newest arrays you created
matrix6 = np.dot(matrix4,matrix5)
# no va a funcionar porque el numero de columnas de la primer matriz no es igual al 
# numero de filas de la segunda matriz, y sabemos que esa condicion se tiene que 
# cumplir para poder efectuar el producto punto entre las matrices correctamente.
# Por lo tanto, para resolver este inconveniente sugiero trasponer la segunda matriz

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
matrix6 = np.dot(matrix4,matrix5.T)
matrix6

# La función np.dot() realiza el producto punto entre a y b 
# Retornará ValueError si la última dimensión de `a` no tiene el mismo tamaño que 
# la penúltima dimensión de `b`; es decir si la cantidad de columnas de a
# es distinta de la cantidad de filas de b arrojará error.

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [5]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(35)

matrix7 = np.random.randint(0, 10, size=(3,6))
matrix8 = np.random.randint(0, 10, size=(3,6))

print(f"El primer arreglo es:\n{matrix7}\nMientras que el segundo es:\n{matrix8}")

El primer arreglo es:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
Mientras que el segundo es:
[[3 9 8 7 5 8]
 [6 0 1 9 9 0]
 [2 2 5 8 3 0]]


In [4]:
# Compare the two arrays with '>'
matrix7 > matrix8

# Compara elemento por elemento entre las dos matrices y verfica
# si el elemento de la primera matriz es mayor que el elemento de
# la segunda matriz, de ser cierto, retorna True, de lo contrario,
# retorna False.

array([[ True, False, False, False,  True, False],
       [ True,  True,  True, False, False,  True],
       [False,  True, False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [3]:
# Compare the two arrays with '>='
matrix7 >= matrix8

array([[ True, False, False, False,  True,  True],
       [ True,  True,  True, False, False,  True],
       [False,  True, False, False,  True,  True]])

In [87]:
# Find which elements of the first array are greater than 7
print(f"El primer arreglo es:\n{matrix7}\nSon sus elementos mayor a 7?\n{matrix7 > 7}")

El primer arreglo es:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
Son sus elementos mayor a 7?
[[ True False False False  True  True]
 [ True  True  True False False  True]
 [False  True False False False False]]


In [6]:
# Which parts of each array are equal? (try using '==')
# print(f"El primer arreglo es:\n{matrix7}\nSon sus elementos iguales a 7?\n{matrix7 == 7}")
matrix7 == matrix8

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [91]:
# Sort one of the arrays you just created in ascending order
np.sort(matrix7)

array([[0, 1, 7, 8, 9, 9],
       [7, 7, 8, 8, 8, 9],
       [0, 2, 3, 3, 5, 9]])

In [14]:
# Sort the indexes of one of the arrays you just created
print(f"The array that we have to sort is:\n{matrix7}")
print("The indices that would sorted the array are:")
np.argsort(matrix7, axis=1)

The array that we have to sort is:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
The indices that would sorted the array are:


array([[3, 2, 1, 5, 0, 4],
       [3, 4, 0, 1, 5, 2],
       [0, 2, 4, 5, 3, 1]], dtype=int64)

Primera fila:     [9 7 1 0 9 8]
        index:     0 1 2 3 4 5
fila ordenada     [0 1 7 8 9 9] valores ordenados
        index:     3 2 1 5 0 4     
si queres ordenar la fila de forma creciente entonces:
lo que estaba en la posicion 3 (el 0) ponelo primero, adelante de todo;
lo que estaba en la posicion 2 (el 1) ponelo segundo;
lo que estaba en la posicion 1 (el 7) ponelo tercero;
lo que estaba en la posicion 5 (el 8) ponelo cuarto ;
lo que estaba en la posicion 0 (el 9) ponelo quinto;
lo que estaba en la posicion 4 (el otro 9) ponelo sexto

Cuando ejecutas np.argsort(matrix7, axis=1), estás ordenando cada fila de la matriz. 
Los valores en cada fila se ordenan, pero lo que argsort devuelve son los índices que 
te permitirían obtener esa ordenación.

La primera fila de la matriz original es [9, 7, 1, 0, 9, 8].
El array de índices resultante para esta fila es [3, 2, 1, 5, 0, 4].
Esto significa lo siguiente:
El valor más pequeño (0) está en la posición 3 de la fila original.
El valor 1 está en la posición 2 de la fila original.
El valor 7 está en la posición 1.
El valor 8 está en la posición 5.
El valor 9 (primer 9) está en la posición 0.
El valor 9 (segundo 9) está en la posición 4.
Por lo tanto, la fila ordenada sería [0, 1, 7, 8, 9, 9] y esos son los índices que te devuelve argsort.

In [16]:
# Find the index with the maximum value in one of the arrays you've created
print(f"The array we have created is is:\n{matrix7}")
print("The index with the maximum value in matrix 7 is:\n")
np.argmax(matrix7, axis=1)

The array we have created is is:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
The index with the maximum value in matrix 7 is:



array([0, 2, 1], dtype=int64)

la primera componente del array dice que el valor maximo de la primera fila está en el indice 0 (que corresponde al primer 9).
la segunda componente del array dice que el valor maximo de la segunda fila está en el indice 2 (que corresponde al 9).
la tercera componente del array dice que el valor maximo de la tercera fila está en el indice 1 (que corresponde al 9).

Primera fila [9, 7, 1, 0, 9, 8]:

El valor máximo en la primera fila es 9.
El valor máximo de la primera fila está en la posición 0 (primer elemento), que es el valor 9.
Segunda fila [8, 8, 9, 7, 7, 8]:

El valor máximo en la segunda fila es 9.
El valor máximo de la segunda fila está en la posición 2, que es el valor 9.
Tercera fila [0, 9, 2, 5, 3, 3]:

El valor máximo en la tercera fila es 9.
El valor máximo de la tercera fila está en la posición 1, que es el valor 9.

El valor máximo es 9 en todas las filas, y np.argmax(matrix7, axis=1) devuelve los índices de las posiciones donde se encuentran estos valores máximos.

El valor máximo de la primera fila está en el índice 0 (que corresponde al primer 9).
El valor máximo de la segunda fila está en el índice 2 (que corresponde al 9).
El valor máximo de la tercera fila está en el índice 1 (que corresponde al 9).

Así que la interpretación sería:

La primera componente del array dice que el valor máximo de la primera fila está en el índice 0 (el primer 9).
La segunda componente del array dice que el valor máximo de la segunda fila está en el índice 2 (el 9 en la tercera posición).
La tercera componente del array dice que el valor máximo de la tercera fila está en el índice 1 (el 9 en la segunda posición).

In [18]:
# Find the index with the minimum value in one of the arrays you've created
print(f"The array we have created is is:\n{matrix7}")
print("The index with the minimu value in matrix 7 is:\n")
np.argmin(matrix7)

# Este metodo busca el índice donde se encuentra el valor mínimo 
# en todo el array de la matriz (sin importar la fila o columna)

# Esto devuelve un solo índice que corresponde al índice lineal dentro del array plano.

The array we have created is is:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
The index with the minimu value in matrix 7 is:



3

El indice en el que se encuentra el valor minimo de todo el array es 3.

El numero mas pequeño de la matriz es el 0 y vemos la primera ocurrencia de
este elemento se da en la posición 3. Por lo tanto, tiene sentido que el
resultado sea 3

En este caso, la respuesta fue 3, lo que significa que el valor mínimo en toda 
la matriz se encuentra en la posición 3 del array plano (es decir, el valor mínimo 
en el array tiene su índice 3 cuando lo "aplanamos" a un solo vector).

La matriz original es:
[[9 7 1 0 9 8]
 [8 8 9 7 7 8]
 [0 9 2 5 3 3]]
Si aplanamos esta matriz en un solo array de 18 elementos, el índice 3 corresponde al siguiente array plano:
[9, 7, 1, 0, 9, 8, 8, 8, 9, 7, 7, 8, 0, 9, 2, 5, 3, 3]
En este array plano, el valor mínimo (0) se encuentra en la posición 3 (empezando desde 0).

In [20]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmin(matrix7, axis=1)

array([3, 3, 0], dtype=int64)

In [21]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(matrix7, axis=0)

array([2, 0, 0, 0, 2, 2], dtype=int64)

In [25]:
# Create an array of normally distributed random numbers
mu = 0    # Media (centro de la distribución)
sigma = 0.1    # Desviación estándar (dispersión de los datos)
matrix9 = np.random.normal(mu, sigma, size=(3,5))
matrix9
# Extrae muestras aleatorias de una distribución normal (gaussiana).

# otra opcion: np.random.randn(3, 5) 

array([[ 0.17640523,  0.04001572,  0.0978738 ,  0.22408932,  0.1867558 ],
       [-0.09772779,  0.09500884, -0.01513572, -0.01032189,  0.04105985],
       [ 0.01440436,  0.14542735,  0.07610377,  0.0121675 ,  0.04438632]])

In [24]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.random.seed(0)
array = np.linspace(1, 100, num=10)
array
# linspase devuelve números espaciados uniformemente en un intervalo especificado.

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.